openapi: 3.0.3
info:
  title: ClassName Service
  description: Swagger View for ClassName Service
  version: 1.0.11
servers:
  - url: http://localhost:8888/
    description: "ClassName"
tags:
  - name: Add a ClassName
paths:
  /className:
    post:
      tags:
        - Add a ClassName
      summary: Create a new ClassName
      description: Create a new ClassName
      operationId: createClassName
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClassName'
        required: true
      responses:
        '201':
          description: Created Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClassName'
        '400':
          description: Already Exists
    put:
      tags:
        - Update a ClassName
      summary: Update an existing ClassName
      operationId: updateClassName
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClassName'
        required: true
      responses:
        '200':
          description: Updated Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClassName'
        '400':
          description: Invalid Id
  /className/{id}:
    get:
      tags:
        - Get a ClassName
      summary: Get a ClassName
      operationId: getClassName
      parameters:
        - name: id
          in: path
          required: true
          explode: true
          schema:
            type: number
            default: 1
      responses:
        '200':
          description: Fetched Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClassName'
        '400':
          description: Invalid Id
    delete:
      tags:
        - Delete a ClassName
      summary: Delete a ClassName
      operationId: deleteClassName
      parameters:
        - name: id
          in: path
          required: true
          explode: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted Successfully
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid Id
    
components:
  schemas:
    ClassName:
      type: object
      properties:
        id:
          type: number
          format: int64
          example: 10
        name:
          type: string
          example: String